- id: '1718518334725'
  alias: 小米电视每日使用时长限制
  description: ''
  triggers:
  - entity_id:
    - sensor.jin_ri_dian_shi_zai_xian_shi_chang
    above: input_number.xiao_mi_dian_shi_mei_ri_shi_yong_shi_chang_shang_xian
    trigger: numeric_state
  - entity_id:
    - device_tracker.c8_28_32_34_f9_c7
    from:
    to: home
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.xiao_mi_dian_shi_shi_chang_xian_zhi_kai_guan
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.jin_ri_dian_shi_zai_xian_shi_chang
      above: input_number.xiao_mi_dian_shi_mei_ri_shi_yong_shi_chang_shang_xian
    - condition: state
      entity_id: device_tracker.c8_28_32_34_f9_c7
      state: home
    - condition: template
      value_template: '{{as_timestamp(now()) - as_timestamp(state_attr(''automation.xin_jian_zi_dong_hua'',''last_triggered''))
        > 300}}'
  actions:
  - device_id: a0ad402ab514b5161c817d3a0c981ef7
    domain: text
    entity_id: be7c34e6b25c1c43b3ec12ff54ba451a
    type: set_value
    value: 小木耳，今日电视使用时长已超上限，十秒后即将自动关闭电视
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - device_id: 85d3ec6226d82be9b40dd0bc25a1c6a4
    domain: select
    entity_id: 0b92916f408f40e24711bcd7a6b071cd
    type: select_option
    option: power
  mode: single
- id: '1718520261178'
  alias: 连续观看电视限制
  description: ''
  triggers:
  - entity_id:
    - sensor.dian_shi_lian_xu_guan_kan_shi_chang
    above: 25
    trigger: numeric_state
  - entity_id:
    - device_tracker.c8_28_32_34_f9_c7
    from:
    to: home
    trigger: state
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.c8_28_32_34_f9_c7
      state: home
    - condition: state
      entity_id: input_boolean.xiao_mi_dian_shi_shi_chang_xian_zhi_kai_guan
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.dian_shi_lian_xu_guan_kan_shi_chang
      above: 25
    - condition: template
      value_template: '

        {{as_timestamp(now()) - as_timestamp(state_attr(''automation.lian_xu_guan_kan_dian_shi_xian_zhi'',''last_triggered''))
        > 300}}'
  actions:
  - device_id: a0ad402ab514b5161c817d3a0c981ef7
    domain: text
    entity_id: be7c34e6b25c1c43b3ec12ff54ba451a
    type: set_value
    value: 小木耳，你已连续看电视超30分钟，十秒后即将自动关闭电视
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - device_id: 85d3ec6226d82be9b40dd0bc25a1c6a4
    domain: select
    entity_id: 0b92916f408f40e24711bcd7a6b071cd
    type: select_option
    option: power
  mode: single
- id: '1734690433738'
  alias: 门口有人自动通知手机
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - camera.madv_miowlv2_fe51_video_doorbell
    attribute: motion_video_time
  conditions: []
  actions:
  - action: notify.mobile_app_iphone_86
    metadata: {}
    data:
      message: 有人在门口逗留
      title: 注意⚠️
      data:
        url: '{{state_attr(''camera.madv_miowlv2_fe51_video_doorbell'',''stream_address'')}}'
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: '2'
      retain: false
      topic: ha/mijia/doorbell/state_changed
  mode: single
- id: '1740894301265'
  alias: 软路由温度高于45度自动打开风扇
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bei_kong_j4125_istoreos_temperature
    above: 45
  conditions:
  - condition: state
    entity_id: switch.ruo_dian_xiang_feng_shan_kong_zhi_qi_switch_1
    state: 'off'
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.ruo_dian_xiang_feng_shan_kong_zhi_qi_switch_1
  mode: single
- id: '1740894596361'
  alias: 软路由温度低于45度关闭风扇
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.bei_kong_j4125_istoreos_temperature
    below: 45
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: switch.ruo_dian_xiang_feng_shan_kong_zhi_qi_switch_1
      state: 'on'
    - condition: template
      value_template: '{{as_timestamp(now()) - as_timestamp(state_attr(''automation.ruan_lu_you_wen_du_gao_yu_45du_zi_dong_da_kai_feng_shan'',''last_triggered''))
        > 300}}'
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.ruo_dian_xiang_feng_shan_kong_zhi_qi_switch_1
  mode: single
- id: '1748754563804'
  alias: 制氧机定时执行任务
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - action: script.unknown
    metadata: {}
    data: {}
  mode: single
- id: '1749252364892'
  alias: 靠近ipad自动亮屏
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - event.lumi_cn_blt_3_1i30u2ej0c801_bmgl01_motion_detected_e_2_1
  conditions: []
  actions:
  - action: notify.mobile_app_jessonde_ipad
    metadata: {}
    data:
      message: 有人靠近中控屏
      title: 注意⚠️
  mode: single
- id: '1750905438899'
  alias: 净水器放水时长检测
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.162727723851771_water_consumption
    for:
      hours: 0
      minutes: 1
      seconds: 0
    above: 0
  conditions: []
  actions:
  - device_id: 8ed43fab53ba8b63b3fd78d009a19923
    domain: text
    entity_id: 15677603dbfe1066936cb56b10be92b8
    type: set_value
    value: 净水器水龙头忘记关了
  mode: single
- id: '1756808480330'
  alias: 新建自动化
  description: ''
  triggers:
  - type: changed_states
    device_id: 85d3ec6226d82be9b40dd0bc25a1c6a4
    entity_id: 5a02fd47b6f30e5d63309ce4d354b48d
    domain: media_player
    trigger: device
  conditions: []
  actions:
  - device_id: 85d3ec6226d82be9b40dd0bc25a1c6a4
    domain: select
    entity_id: 0b92916f408f40e24711bcd7a6b071cd
    type: select_option
    option: power
  mode: single
- id: '1761651840426'
  alias: HA处理器占用过高提示
  description: ''
  triggers:
  - type: value
    device_id: 9efa4c9a210f6711a1f46dcf264c05e5
    entity_id: 564a27d79e75a080c93eca089fc13827
    domain: sensor
    trigger: device
    above: 50
    for:
      hours: 0
      minutes: 0
      seconds: 30
  conditions: []
  actions:
  - action: notify.mobile_app_iphone_86
    metadata: {}
    data:
      message: HA处理器占用过高，需要检查
      title: 警告
  - action: profiler.start
    metadata: {}
    data:
      seconds: 60
  mode: single
- id: '1768270145156'
  alias: 在家->出门
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.mu_er_ba_ba
    from:
    to:
    - not_home
  - trigger: state
    entity_id:
    - person.mu_er_ma_ma
    from:
    to:
    - not_home
  - trigger: state
    entity_id:
    - person.mu_er_nai_nai
    from:
    to:
    - not_home
  - trigger: state
    entity_id:
    - person.mu_er_ye_ye
    from:
    to:
    - not_home
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.mu_er_ba_ba
      state:
      - not_home
    - condition: state
      entity_id: person.mu_er_ma_ma
      state:
      - not_home
    - condition: state
      entity_id: person.mu_er_nai_nai
      state:
      - not_home
    - condition: state
      entity_id: person.mu_er_ye_ye
      state:
      - not_home
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.chang_jing_mo_shi_xuan_ze
    data:
      option: 出门模式
  mode: single
- id: '1768280507352'
  alias: 出门->在家
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.mu_er_ba_ba
    from:
    to:
    - home
  - trigger: state
    entity_id:
    - person.mu_er_ma_ma
    from:
    to:
    - home
  - trigger: state
    entity_id:
    - person.mu_er_nai_nai
    from:
    to:
    - home
  - trigger: state
    entity_id:
    - person.mu_er_ye_ye
    from:
    to:
    - home
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.mu_er_ba_ba
      state:
      - home
    - condition: state
      entity_id: person.mu_er_ma_ma
      state:
      - home
    - condition: state
      entity_id: person.mu_er_nai_nai
      state:
      - home
    - condition: state
      entity_id: person.mu_er_ye_ye
      state:
      - home
  - condition: state
    entity_id: input_select.chang_jing_mo_shi_xuan_ze
    state:
    - 出门模式
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.chang_jing_mo_shi_xuan_ze
    data:
      option: 在家模式
  mode: single
- id: '1768281131653'
  alias: 在家->晚安
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.zhu_wo_kai_deng_shu_liang
    below: 1
  - trigger: numeric_state
    entity_id:
    - sensor.ci_wo_kai_deng_shu_liang
    below: 1
  - trigger: time
    at: '22:35:00'
  conditions:
  - condition: and
    conditions:
    - condition: time
      after: '22:30:00'
    - condition: numeric_state
      entity_id: sensor.zhu_wo_kai_deng_shu_liang
      below: 1
    - condition: numeric_state
      entity_id: sensor.ci_wo_kai_deng_shu_liang
      below: 1
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.chang_jing_mo_shi_xuan_ze
      state:
      - 出门模式
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.chang_jing_mo_shi_xuan_ze
    data:
      option: 晚安模式
  mode: single
- id: '1768323484390'
  alias: 晚安->在家
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions:
  - condition: state
    entity_id: input_select.chang_jing_mo_shi_xuan_ze
    state:
    - 晚安模式
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.chang_jing_mo_shi_xuan_ze
    data:
      option: 在家模式
  mode: single
