# Loads default set of integrations. Do not remove.
default_config:
mobile_app:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/community/hass-hue-icons/hass-hue-icons.js
    - /local/community/custom-icons/custom-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:  # Core configuration block
  customize: !include customize.yaml  # Correct reference method
  # customize_domain: !include domain_customize.yaml  # Optional domain-wide customization
logger:
  default: info
  logs:
    custom_components.pyscript: info
 

environment_variable:
  OPENAI_BASE_URL: https://api.deepseek.com/v1

# 允许代理
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.31.1 # Add the IP address of the proxy server


# 自定义历史数据统计
sensor:
  - platform: history_stats
    name: 今日电视在线时长
    unique_id: time.tv_online_today
    entity_id: device_tracker.c8_28_32_34_f9_c7
    state: "home"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

# # iStoreOS device track
device_tracker:
  - platform: luci
    host: 192.168.31.1
    username: root
    password: Xx20121020;


# istore os mqtt sensor and device
### iStoreOS MQTT
mqtt:
  sensor: !include mqtt/istoreos_sensors.yaml
  device_tracker: !include mqtt/home_devices.yaml

# 国家电网(32-1504)
template:
  - trigger:
      - trigger: event
        event_type: bubble_card_update_modules
    sensor:
      - name: "Bubble Card Modules"
        state: "saved"
        icon: "mdi:puzzle"
        attributes:
          modules: "{{ trigger.event.data.modules }}"
          last_updated: "{{ trigger.event.data.last_updated }}"
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.electricity_charge_balance_2902
    sensor:
      - name: electricity_charge_balance_2902
        unique_id: electricity_charge_balance_2902
        state: "{{ states('sensor.electricity_charge_balance_2902') }}"
        state_class: total
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.last_electricity_usage_2902
    sensor:
      - name: last_electricity_usage_2902
        unique_id: last_electricity_usage_2902
        state: "{{ states('sensor.last_electricity_usage_2902') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_usage_2902
    sensor:
      - name: month_electricity_usage_2902
        unique_id: month_electricity_usage_2902
        state: "{{ states('sensor.month_electricity_usage_2902') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_charge_2902
    sensor:
      - name: month_electricity_charge_2902
        unique_id: month_electricity_charge_2902
        state: "{{ states('sensor.month_electricity_charge_2902') }}"
        state_class: measurement
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_usage_2902
    sensor:
      - name: yearly_electricity_usage_2902
        unique_id: yearly_electricity_usage_2902
        state: "{{ states('sensor.yearly_electricity_usage_2902') }}"
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_charge_2902
    sensor:
      - name: yearly_electricity_charge_2902
        unique_id: yearly_electricity_charge_2902
        state: "{{ states('sensor.yearly_electricity_charge_2902') }}"
        state_class: total_increasing
        unit_of_measurement: "CNY"
        device_class: monetary

  # 国家电网(充电桩)
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.electricity_charge_balance_4702
    sensor:
      - name: electricity_charge_balance_4702
        unique_id: electricity_charge_balance_4702
        state: "{{ states('sensor.electricity_charge_balance_4702') }}"
        state_class: total
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.last_electricity_usage_4702
    sensor:
      - name: last_electricity_usage_4702
        unique_id: last_electricity_usage_4702
        state: "{{ states('sensor.last_electricity_usage_4702') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_usage_4702
    sensor:
      - name: month_electricity_usage_4702
        unique_id: month_electricity_usage_4702
        state: "{{ states('sensor.month_electricity_usage_4702') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_charge_4702
    sensor:
      - name: month_electricity_charge_4702
        unique_id: month_electricity_charge_4702
        state: "{{ states('sensor.month_electricity_charge_4702') }}"
        state_class: measurement
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_usage_4702
    sensor:
      - name: yearly_electricity_usage_4702
        unique_id: yearly_electricity_usage_4702
        state: "{{ states('sensor.yearly_electricity_usage_4702') }}"
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_charge_4702
    sensor:
      - name: yearly_electricity_charge_4702
        unique_id: yearly_electricity_charge_4702
        state: "{{ states('sensor.yearly_electricity_charge_4702') }}"
        state_class: total_increasing
        unit_of_measurement: "CNY"
        device_class: monetary
