# Loads default set of integrations. Do not remove.
default_config:
mobile_app:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /local/community/hass-hue-icons/hass-hue-icons.js
    - /local/community/custom-icons/custom-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    custom_components.pyscript: info

# 允许代理
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.31.1 # Add the IP address of the proxy server

# 自定义历史数据统计
sensor:
  - platform: history_stats
    name: 今日电视在线时长
    unique_id: time.tv_online_today
    entity_id: device_tracker.c8_28_32_34_f9_c7
    state: "home"
    type: time
    start: "{{ today_at() }}"
    end: "{{ now() }}"

# iStoreOS device track
device_tracker:
  - platform: luci
    host: 192.168.31.1
    username: root
    password: Xx20121020;

# istore os mqtt sensor and device
### iStoreOS MQTT
mqtt:
  sensor:
    # mem
    - name: iStoreOS RAM used
      state_topic: collectd/iStoreOS/memory/memory-used
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(value.split(':')[1].split('\x00')[0] | float / (16 * 1024 * 10000))}}"
      unique_id: ram_used
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

    # cpu
    - name: iStoreOS cpu-0
      state_topic: collectd/iStoreOS/cpu-0/percent-idle
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(100 - (value.split(':')[1].split('\x00')[0] | float)) }}"
      unique_id: cpu-0_used
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS cpu-1
      state_topic: collectd/iStoreOS/cpu-1/percent-idle
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(100 - (value.split(':')[1].split('\x00')[0] | float)) }}"
      unique_id: cpu-1_used
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS cpu-2
      state_topic: collectd/iStoreOS/cpu-2/percent-idle
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(100 - (value.split(':')[1].split('\x00')[0] | float)) }}"
      unique_id: cpu-2_used
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS cpu-3
      state_topic: collectd/iStoreOS/cpu-3/percent-idle
      unit_of_measurement: "%"
      value_template: "{{ '%.2f' | format(100 - (value.split(':')[1].split('\x00')[0] | float)) }}"
      unique_id: cpu-3_used
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

    # br-lan interface
    - name: iStoreOS br-lan TX
      state_topic: collectd/iStoreOS/interface-br-lan/if_octets
      unit_of_measurement: KB/s
      value_template: "{{ '%.2f' | format(value.split(':')[1] | float / 1024)}}"
      unique_id: br-lan-tx-transfer
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS br-lan RX
      state_topic: collectd/iStoreOS/interface-br-lan/if_octets
      unit_of_measurement: KB/s
      value_template: "{{ '%.2f' | format(value.split(':')[2].split('\x00')[0] | float / 1024) }}"
      unique_id: br-lan-rx-transfer
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS br-lan packets
      state_topic: collectd/iStoreOS/interface-br-lan/if_packets
      unit_of_measurement: packets/s
      value_template: "{{ value.split(':')[1] | int + value.split(':')[2].split('\x00')[0] | int }}"
      unique_id: br-lan-packets
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

    # uptime
    - name: iStoreOS uptime
      state_topic: collectd/iStoreOS/uptime/uptime
      unit_of_measurement: days
      value_template: "{{ (value.split(':')[1].split('\x00')[0] | float / 86400) | round(1) }}"
      unique_id: ap_uptime
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

    # temperature
    - name: iStoreOS temperature
      state_topic: collectd/iStoreOS/thermal-thermal_zone0/temperature
      unit_of_measurement: °C
      value_template: "{{ value.split(':')[1].split('\x00')[0] | int }}"
      unique_id: ap_temp
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

    # device
    - name: iStoreOS online devices
      state_topic: collectd/iStoreOS/exec-device-infos/count-online_count
      unit_of_measurement: 个
      value_template: "{{ value.split(':')[1].split('\x00')[0] | int }}"
      unique_id: online_device_count
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控
    - name: iStoreOS offline devices
      state_topic: collectd/iStoreOS/exec-device-infos/count-offline_count
      unit_of_measurement: 个
      value_template: "{{ value.split(':')[1].split('\x00')[0] | int }}"
      unique_id: offline_device_count
      device:
        identifiers: G30S
        name: 倍控J4125
        model: J4125
        manufacturer: 倍控

# 国家电网(32-1504)
template:
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.electricity_charge_balance_2902
    sensor:
      - name: electricity_charge_balance_2902
        unique_id: electricity_charge_balance_2902
        state: "{{ states('sensor.electricity_charge_balance_2902') }}"
        state_class: total
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.last_electricity_usage_2902
    sensor:
      - name: last_electricity_usage_2902
        unique_id: last_electricity_usage_2902
        state: "{{ states('sensor.last_electricity_usage_2902') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_usage_2902
    sensor:
      - name: month_electricity_usage_2902
        unique_id: month_electricity_usage_2902
        state: "{{ states('sensor.month_electricity_usage_2902') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_charge_2902
    sensor:
      - name: month_electricity_charge_2902
        unique_id: month_electricity_charge_2902
        state: "{{ states('sensor.month_electricity_charge_2902') }}"
        state_class: measurement
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_usage_2902
    sensor:
      - name: yearly_electricity_usage_2902
        unique_id: yearly_electricity_usage_2902
        state: "{{ states('sensor.yearly_electricity_usage_2902') }}"
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_charge_2902
    sensor:
      - name: yearly_electricity_charge_2902
        unique_id: yearly_electricity_charge_2902
        state: "{{ states('sensor.yearly_electricity_charge_2902') }}"
        state_class: total_increasing
        unit_of_measurement: "CNY"
        device_class: monetary

  # 国家电网(充电桩)
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.electricity_charge_balance_4702
    sensor:
      - name: electricity_charge_balance_4702
        unique_id: electricity_charge_balance_4702
        state: "{{ states('sensor.electricity_charge_balance_4702') }}"
        state_class: total
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.last_electricity_usage_4702
    sensor:
      - name: last_electricity_usage_4702
        unique_id: last_electricity_usage_4702
        state: "{{ states('sensor.last_electricity_usage_4702') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy
  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_usage_4702
    sensor:
      - name: month_electricity_usage_4702
        unique_id: month_electricity_usage_4702
        state: "{{ states('sensor.month_electricity_usage_4702') }}"
        state_class: measurement
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.month_electricity_charge_4702
    sensor:
      - name: month_electricity_charge_4702
        unique_id: month_electricity_charge_4702
        state: "{{ states('sensor.month_electricity_charge_4702') }}"
        state_class: measurement
        unit_of_measurement: "CNY"
        device_class: monetary

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_usage_4702
    sensor:
      - name: yearly_electricity_usage_4702
        unique_id: yearly_electricity_usage_4702
        state: "{{ states('sensor.yearly_electricity_usage_4702') }}"
        state_class: total_increasing
        unit_of_measurement: "kWh"
        device_class: energy

  - trigger:
      - platform: event
        event_type: state_changed
        event_data:
          entity_id: sensor.yearly_electricity_charge_4702
    sensor:
      - name: yearly_electricity_charge_4702
        unique_id: yearly_electricity_charge_4702
        state: "{{ states('sensor.yearly_electricity_charge_4702') }}"
        state_class: total_increasing
        unit_of_measurement: "CNY"
        device_class: monetary
